exclude: .idea|.git|.vscode|.venv
default_stages: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: autoupdate
        name: autoupdate
        entry: pre-commit
        language: system
        pass_filename: false
        args: [autoupdate]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys", "--indent", "2"]
        files: \.(json)$
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
